name: Terraform

on:
  push:
    branches: [main]
    paths:
      - terraform/**
      - "!**.tfstate"
      - "!**.tfstate.encrypted"
  pull_request:
    paths: [terraform/**]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Download Terraform State
        uses: badgerhobbs/terraform-state@v2
        with:
          encryption_key: ${{ secrets.TERRAFORM_STATE_ENCRYPTION_KEY }}
          operation: download
          location: artifact
          directory: terraform
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -no-color
        env:
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -no-color
        env:
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Upload Terraform State
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: badgerhobbs/terraform-state@v2
        with:
          encryption_key: ${{ secrets.TERRAFORM_STATE_ENCRYPTION_KEY }}
          operation: upload
          location: artifact
          directory: terraform
          github_token: ${{ secrets.GITHUB_TOKEN }}
